server:
  port: 8000

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 43.200.124.135
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://13.124.61.210:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://socoa.online'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: sso-service
          uri: http://localhost:8000
          predicates:
            - Path=/user-service/**

        - id: company-service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/company-service/**

        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**

        - id: complaint-service
          uri: lb://COMPLAINT-SERVICE
          predicates:
            - Path=/complaint-service/**

        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/**

        - id: mypage-service
          uri: lb://MYPAGE-SERVICE
          predicates:
            - Path=/mypage-service/**
