server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: company-service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/company-service/**

        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**

        - id: complaint-service
          uri: lb://COMPLAINT-SERVICE
          predicates:
            - Path=/complaint-service/**

        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/**

        - id: mypage-service
          uri: lb://MYPAGE-SERVICE
          predicates:
            - Path=/mypage-service/**