server:
  port: 8000

eureka:
  instance:
    hostname: gateway.socoa.online
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://13.124.61.210:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allow-credentials: true
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: sso-service
          uri: http://localhost:8000
          predicates:
            - Path=/user-service/**

        - id: company-service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/company-service/**

        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/course-service/**

        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**

        - id: complaint-service
          uri: lb://COMPLAINT-SERVICE
          predicates:
            - Path=/complaint-service/**

        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/**

        - id: mypage-service
          uri: lb://MYPAGE-SERVICE
          predicates:
            - Path=/mypage-service/**
